name: issue-tracker-dev

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_PATH: /data/database.sqlite
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-dev-secret-change-me}
      BETTER_AUTH_BASE_URL: http://localhost:3000
      CORS_ORIGINS: http://localhost:5173
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - issues-db:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      backend:
        condition: service_healthy

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      API_BASE_URL: http://backend:3000/api
      PORT: "4000"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  issues-db:
