name: issue-tracker-prod

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      DATABASE_PATH: /data/database.sqlite
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_BASE_URL: ${BETTER_AUTH_BASE_URL:-http://localhost}
      CORS_ORIGINS: ${FRONTEND_URL:-http://localhost}
      NODE_ENV: production
      LOG_LEVEL: info
    volumes:
      - issues-db:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health/live"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      API_BASE_URL: http://backend:3000/api
      PORT: "4000"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  issues-db:
